from __future__ import annotations

import json
from pathlib import Path

import pytest

import sef.cli as cli_module
from sef.cli import main


def test_cli_validates_repository_yaml_config(capsys) -> None:
    pytest.importorskip("yaml")

    config_path = Path("examples/pipeline.yaml")
    exit_code = main(["validate", str(config_path)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert f"valid: {config_path}" in captured.out
    assert "schema_version: 1.0" in captured.out


def test_cli_validates_repository_aruco_yaml_config(tmp_path: Path, capsys) -> None:
    pytest.importorskip("yaml")
    config_path = tmp_path / "pipeline_aruco.yaml"
    config_path.write_text(
        """
schema_version: "1.0"
pipeline:
  frame_extractor:
    name: opencv_buffered
    params:
      path: videos/input.mp4
      config:
        max_frames: 1
  signal_extractor:
    name: aruco_marker
  analyzers:
    - name: aruco_displacement
""".lstrip(),
        encoding="utf-8",
    )

    exit_code = main(["validate", str(config_path)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert f"valid: {config_path}" in captured.out


def test_cli_lists_builtin_components(capsys) -> None:
    exit_code = main(["components", "list", "--category", "analyzer"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "vertical_position" in captured.out


def test_cli_inspects_builtin_component(capsys) -> None:
    exit_code = main(["components", "inspect", "vertical_position"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "category: analyzer" in captured.out
    assert "input: ISignal" in captured.out
    assert "yaml_example:" in captured.out


def test_cli_prints_version(capsys) -> None:
    exit_code = main(["version"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "sef:" in captured.out
    assert "python:" in captured.out
    assert "install_path:" in captured.out


def test_cli_prints_config_schema(capsys) -> None:
    exit_code = main(["config", "schema", "--format", "json"])

    captured = capsys.readouterr()
    assert exit_code == 0
    payload = json.loads(captured.out)
    assert "frame_processors" in payload["properties"]["pipeline"]["properties"]
    assert "runtime" in payload["properties"]["pipeline"]["properties"]


def test_cli_init_creates_default_scaffold(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)

    exit_code = main(["init"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "template: default" in captured.out
    assert (tmp_path / "pipeline.yaml").exists()
    assert (tmp_path / "plugins").is_dir()
    assert (tmp_path / "videos").is_dir()
    assert (tmp_path / "outputs").is_dir()
    assert (tmp_path / "README.md").exists()


def test_cli_init_tracking_demo_has_expected_video_path(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)

    exit_code = main(["init", "tracking-demo"])

    assert exit_code == 0
    pipeline_yaml = (tmp_path / "pipeline.yaml").read_text(encoding="utf-8")
    assert "videos/input.mp4" in pipeline_yaml
    assert "start_box: [100, 100, 80, 80]" in pipeline_yaml
    assert not (tmp_path / "videos" / "input.mp4").exists()


def test_cli_init_does_not_overwrite_existing_file_without_force(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)
    pipeline_path = tmp_path / "pipeline.yaml"
    pipeline_path.write_text("user-owned\n", encoding="utf-8")

    exit_code = main(["init"])

    assert exit_code == 0
    assert pipeline_path.read_text(encoding="utf-8") == "user-owned\n"


def test_cli_init_force_overwrites_only_scaffold_file(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)
    assert main(["init"]) == 0
    pipeline_path = tmp_path / "pipeline.yaml"
    pipeline_path.write_text("# Generated by sef init\nstale: true\n", encoding="utf-8")

    exit_code = main(["init", "--force"])

    assert exit_code == 0
    assert "schema_version" in pipeline_path.read_text(encoding="utf-8")


def test_cli_validate_unknown_field_is_warning_by_default(tmp_path: Path, capsys) -> None:
    config_path = _write_json_config(tmp_path, {"unexpected": True})

    exit_code = main(["validate", str(config_path)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "valid:" in captured.out
    assert "Unknown field `pipeline.unexpected`" in captured.err


def test_cli_validate_strict_treats_unknown_field_as_error(tmp_path: Path, capsys) -> None:
    config_path = _write_json_config(tmp_path, {"unexpected": True})

    exit_code = main(["validate", str(config_path), "--strict"])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "Unknown field `pipeline.unexpected`" in captured.err


def test_cli_validate_reports_top_level_unknown_fields(tmp_path: Path, capsys) -> None:
    config_path = _write_json_config(tmp_path)
    payload = json.loads(config_path.read_text(encoding="utf-8"))
    payload["unexpected_top_level"] = True
    config_path.write_text(json.dumps(payload), encoding="utf-8")

    exit_code = main(["validate", str(config_path)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "Unknown field `config.unexpected_top_level`" in captured.err


def test_cli_inspects_local_plugin(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)
    _write_local_plugin(tmp_path, suffix="inspect")

    exit_code = main(["components", "inspect", "cli_local_analyzer_inspect"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "cli_local_analyzer_inspect" in captured.out
    assert "optional_params:" in captured.out
    assert "scale=1" in captured.out


def test_cli_run_dry_run_explain_uses_local_plugins(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)
    _write_local_plugin(tmp_path, suffix="dry_run")
    config_path = _write_local_plugin_config(tmp_path, suffix="dry_run")

    exit_code = main(["run", str(config_path), "--dry-run", "--explain"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "Pipeline execution plan:" in captured.out
    assert "dry_run:" in captured.out
    assert "cli_local_analyzer_dry_run" in captured.out or "FunctionAnalyzer" in captured.out


def test_cli_run_output_writes_summary_config_and_plan(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)
    _write_local_plugin(tmp_path, suffix="output")
    config_path = _write_local_plugin_config(tmp_path, suffix="output")
    output_dir = tmp_path / "run-output"

    exit_code = main(["run", str(config_path), "--output", str(output_dir)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "output:" in captured.out
    assert (output_dir / "summary.json").exists()
    assert (output_dir / "config.normalized.json").exists()
    assert (output_dir / "execution_plan.txt").exists()
    assert list((output_dir / "artifacts").glob("*.md"))


def test_cli_doctor_warning_only_exit_zero(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        cli_module,
        "_doctor_dependencies",
        lambda diagnostics: diagnostics.add_warning("synthetic warning"),
    )
    monkeypatch.setattr(cli_module, "_doctor_opencv_trackers", lambda diagnostics: None)
    monkeypatch.setattr(cli_module, "_doctor_matplotlib_cache", lambda diagnostics: None)

    exit_code = main(["doctor"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "sef: warning:" in captured.err


def test_cli_doctor_missing_config_is_blocking(tmp_path: Path, monkeypatch, capsys) -> None:
    monkeypatch.chdir(tmp_path)

    exit_code = main(["doctor", "--config", "missing.json"])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "Config check failed" in captured.err


def _write_json_config(tmp_path: Path, extra_pipeline: dict[str, object] | None = None) -> Path:
    config = _minimal_builtin_config()
    config["pipeline"].update(extra_pipeline or {})
    config_path = tmp_path / "pipeline.json"
    config_path.write_text(json.dumps(config), encoding="utf-8")
    return config_path


def _minimal_builtin_config() -> dict[str, object]:
    return {
        "schema_version": "1.0",
        "pipeline": {
            "frame_extractor": {
                "name": "opencv_buffered",
                "params": {"path": "videos/input.mp4", "config": {"max_frames": 1}},
            },
            "frame_processors": [],
            "signal_extractor": {
                "name": "opencv_tracker",
                "params": {"tracker_type": "MIL", "start_box": [1, 1, 2, 2]},
            },
            "signal_cleaners": [],
            "analyzers": [{"name": "vertical_position"}],
            "visualizers": [],
        },
    }


def _write_local_plugin(tmp_path: Path, *, suffix: str) -> None:
    plugin_dir = tmp_path / "plugins"
    plugin_dir.mkdir()
    plugin_dir.joinpath("custom_components.py").write_text(
        f"""
from __future__ import annotations

import numpy as np
import sef
from sef.core.artifacts.Frame import Frame
from sef.core.artifacts.buffer.FrameBuffer import FrameBuffer
from sef.core.artifacts.Signal import Signal
from sef.core.artifacts.signal_sample.BoxSignalSample import BoxSignalSample
from sef.core.artifacts.data.TwoDimGraphData import TwoDimGraphData
from sef.core.visualization.VisualArtifact import TextArtifact


@sef.frame_extractor("cli_local_frames_{suffix}")
def frames():
    buffer = FrameBuffer(frames=[Frame(image=np.zeros((4, 4, 3), dtype=np.uint8), index=0, timestamp_seconds=0.0)])
    buffer.close()
    return buffer


@sef.signal_extractor("cli_local_signal_{suffix}")
def signal(buffer):
    return Signal([BoxSignalSample(frame_index=0, box=(1, 1, 2, 2), centroid=(2.0, 2.0), timestamp_seconds=0.0)])


@sef.analyzer("cli_local_analyzer_{suffix}")
def analyzer(signal, scale=1):
    return TwoDimGraphData(x=[0.0], y=[float(scale)], label="local")


@sef.visualizer("cli_local_visualizer_{suffix}")
def visualizer(data):
    return TextArtifact(kind="text", content=f"# {{data.label}}")
""",
        encoding="utf-8",
    )


def _write_local_plugin_config(tmp_path: Path, *, suffix: str) -> Path:
    config = {
        "schema_version": "1.0",
        "pipeline": {
            "frame_extractor": {"name": f"cli_local_frames_{suffix}"},
            "frame_processors": [],
            "signal_extractor": {"name": f"cli_local_signal_{suffix}"},
            "signal_cleaners": [],
            "analyzers": [{"name": f"cli_local_analyzer_{suffix}", "params": {"scale": 2}}],
            "visualizers": [{"name": f"cli_local_visualizer_{suffix}", "result_indices": [0]}],
        },
    }
    config_path = tmp_path / "pipeline.json"
    config_path.write_text(json.dumps(config), encoding="utf-8")
    return config_path
