from __future__ import annotations

import argparse
import hashlib
import importlib
import importlib.metadata
import importlib.util
import inspect
import json
import os
import platform
import shutil
import sys
import traceback
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import sef
from sef.api import default_registry, from_config, normalize_config
from sef.cli.output import renderer_for
from sef.core.errors import (
    ConfigSchemaError,
    DuplicatePluginRegistrationError,
    PipelineConfigurationError,
    PipelineExecutionError,
)
from sef.core.interfaces.StageCapabilities import StageCapabilities
from sef.core.pipeline.PipelineExecutionPlan import PipelineExecutionPlan
from sef.core.pipeline.PipelineExportUtils import json_dumps, to_exportable_data, yaml_dumps
from sef.core.plugins import PluginCategory, PluginDefinition, PluginRegistry
from sef.core.visualization.PipelineOutputs import PipelineOutputs
from sef.core.visualization.VisualArtifact import (
    DeferredVideoArtifact,
    ImageArtifact,
    JsonArtifact,
    TableArtifact,
    TextArtifact,
    VideoArtifact,
    VideoFileArtifact,
    VisualArtifact,
)

_SCAFFOLD_FILE_MARKER = "# Generated by sef init"
_DEFAULT_CONFIG_NAME = "pipeline.yaml"
_PLUGIN_DIR_NAME = "plugins"
_VIDEO_DIR_NAME = "videos"
_OUTPUT_DIR_NAME = "outputs"
_UNKNOWN_FIELD_DOC = "Remove the field or move custom values under params/metadata."


def _print_status(level: str, message: str) -> None:
    renderer_for(sys.stdout).print_status(level, message)


def _print_ok(message: str) -> None:
    _print_status("ok", message)


def _print_info(message: str) -> None:
    _print_status("info", message)


def main(argv: Sequence[str] | None = None) -> int:
    """Run the SEF command-line interface."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.handler(args))
    except Exception as exc:  # noqa: BLE001 - CLI boundary converts all failures to readable errors.
        debug = bool(getattr(args, "debug", False))
        CliDiagnostics.from_exception(exc).print(debug=debug)
        return 1


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="sef",
        description="Run, validate, inspect, and scaffold SEF pipeline projects.",
    )
    parser.add_argument("--debug", action="store_true", help="Print full tracebacks for CLI errors.")
    subcommands = parser.add_subparsers(dest="command", required=True)

    init_parser = subcommands.add_parser("init", help="Create a SEF project scaffold.")
    init_parser.add_argument(
        "template",
        nargs="?",
        choices=("tracking-demo",),
        help="Optional scaffold template. Currently supports tracking-demo.",
    )
    init_parser.add_argument("--force", action="store_true", help="Overwrite SEF scaffold files created by sef init.")
    init_parser.set_defaults(handler=_init_project)

    doctor_parser = subcommands.add_parser("doctor", help="Inspect the local SEF environment.")
    doctor_parser.add_argument("--config", default=None, help="Optional pipeline config to validate during checks.")
    doctor_parser.set_defaults(handler=_doctor)

    run_parser = subcommands.add_parser("run", help="Run a YAML or JSON pipeline config.")
    run_parser.add_argument("config", help="Path to a .yaml, .yml, or .json pipeline config.")
    run_parser.add_argument("--pipeline-id", help="Optional pipeline id for metadata and artifacts.")
    run_parser.add_argument("--dry-run", action="store_true", help="Build and explain the pipeline without executing it.")
    run_parser.add_argument("--explain", action="store_true", help="Print the execution plan.")
    run_parser.add_argument("--output", help="Directory for run summaries, plans, normalized config, and artifacts.")
    run_parser.add_argument("--debug", action="store_true", help="Print full tracebacks for CLI errors.")
    run_parser.set_defaults(handler=_run_pipeline)

    validate_parser = subcommands.add_parser("validate", help="Validate a YAML or JSON pipeline config.")
    validate_parser.add_argument("config", help="Path to a .yaml, .yml, or .json pipeline config.")
    validate_parser.add_argument("--strict", action="store_true", help="Treat unknown config fields as errors.")
    validate_parser.add_argument("--debug", action="store_true", help="Print full tracebacks for CLI errors.")
    validate_parser.set_defaults(handler=_validate_pipeline)

    components_parser = subcommands.add_parser("components", help="Inspect registered SEF components.")
    component_subcommands = components_parser.add_subparsers(dest="components_command", required=True)

    list_parser = component_subcommands.add_parser("list", help="List registered component plugins.")
    list_parser.add_argument(
        "--category",
        choices=tuple(category.value for category in PluginCategory),
        help="Filter components by plugin category.",
    )
    list_parser.add_argument("--json", action="store_true", help="Print component descriptors as JSON.")
    list_parser.set_defaults(handler=_list_components)

    inspect_parser = component_subcommands.add_parser("inspect", help="Inspect one component in detail.")
    inspect_parser.add_argument("name", help="Component name or alias to inspect.")
    inspect_parser.add_argument(
        "--category",
        choices=tuple(category.value for category in PluginCategory),
        help="Disambiguate components that share a name across categories.",
    )
    inspect_parser.add_argument("--json", action="store_true", help="Print the inspection payload as JSON.")
    inspect_parser.set_defaults(handler=_inspect_component)

    version_parser = subcommands.add_parser("version", help="Print SEF version and installation details.")
    version_parser.set_defaults(handler=_version)

    config_parser = subcommands.add_parser("config", help="Inspect SEF public config helpers.")
    config_subcommands = config_parser.add_subparsers(dest="config_command", required=True)
    schema_parser = config_subcommands.add_parser("schema", help="Print the practical public config schema.")
    schema_parser.add_argument("--format", choices=("json", "yaml"), default="json", help="Output format.")
    schema_parser.set_defaults(handler=_config_schema)

    return parser


@dataclass(slots=True)
class DiagnosticItem:
    """Structured CLI diagnostic item rendered by `CliDiagnostics`."""

    severity: str
    message: str
    cause: str | None = None
    suggestion: str | None = None


@dataclass(slots=True)
class CliDiagnostics:
    """Collects human-readable CLI diagnostics and maps them to exit codes."""

    items: list[DiagnosticItem] = field(default_factory=list)
    exception: BaseException | None = None

    @classmethod
    def from_exception(cls, exc: BaseException) -> CliDiagnostics:
        """Build a diagnostic payload for an unexpected command failure."""
        if isinstance(exc, FileNotFoundError):
            return cls(
                [
                    DiagnosticItem(
                        "error",
                        str(exc),
                        cause="The requested path does not exist.",
                        suggestion="Check the path or run `sef init` to create a starter project.",
                    )
                ],
                exception=exc,
            )

        if isinstance(exc, PermissionError):
            return cls(
                [
                    DiagnosticItem(
                        "error",
                        str(exc),
                        cause="The CLI cannot read or write a required path.",
                        suggestion="Check directory permissions or choose a writable --output directory.",
                    )
                ],
                exception=exc,
            )

        if isinstance(exc, PipelineConfigurationError):
            return cls(
                [
                    DiagnosticItem(
                        "error",
                        str(exc),
                        cause="The pipeline config could not be resolved into executable components.",
                        suggestion="Run `sef validate <config> --strict` and inspect component names/params.",
                    )
                ],
                exception=exc,
            )

        if isinstance(exc, PipelineExecutionError):
            return cls(
                [
                    DiagnosticItem(
                        "error",
                        str(exc),
                        cause="The pipeline started but a runtime stage failed.",
                        suggestion="Re-run with `--debug` for a traceback and inspect the failing component.",
                    )
                ],
                exception=exc,
            )

        return cls(
            [
                DiagnosticItem(
                    "error",
                    str(exc) or type(exc).__name__,
                    cause="The CLI command failed before completion.",
                    suggestion="Re-run with `--debug` to include the full traceback.",
                )
            ],
            exception=exc,
        )

    def add_warning(self, message: str, *, cause: str | None = None, suggestion: str | None = None) -> None:
        """Append a non-blocking diagnostic."""
        self.items.append(DiagnosticItem("warning", message, cause, suggestion))

    def add_error(self, message: str, *, cause: str | None = None, suggestion: str | None = None) -> None:
        """Append a blocking diagnostic."""
        self.items.append(DiagnosticItem("error", message, cause, suggestion))

    @property
    def has_errors(self) -> bool:
        """Return True when at least one item should fail the command."""
        return any(item.severity == "error" for item in self.items)

    def extend(self, items: Sequence[DiagnosticItem]) -> None:
        """Append diagnostics from another command layer."""
        self.items.extend(items)

    def print(self, *, debug: bool = False, stream=None) -> None:
        """Render collected diagnostics."""
        target = stream or sys.stderr
        renderer = renderer_for(target)
        for item in self.items:
            label = "error" if item.severity == "error" else "warning"
            renderer.print_status(label, item.message, stream=target)
            if item.cause:
                renderer.print_detail("cause", item.cause, stream=target)
            if item.suggestion:
                renderer.print_detail("suggestion", item.suggestion, stream=target)
        if debug and self.exception is not None:
            print("", file=target)
            traceback.print_exception(self.exception, file=target)

    def exit_code(self) -> int:
        """Return the CLI exit code represented by these diagnostics."""
        return 1 if self.has_errors else 0


@dataclass(frozen=True, slots=True)
class PluginImportResult:
    """Summary for local plugin loading."""

    loaded_paths: tuple[Path, ...]
    diagnostics: tuple[DiagnosticItem, ...]


class CliRegistryLoader:
    """Loads built-in SEF plugins plus local `plugins/*.py` decorator plugins."""

    def __init__(self, project_root: Path | str | None = None) -> None:
        self._project_root = Path(project_root or Path.cwd()).resolve()
        self._plugin_dir = self._project_root / _PLUGIN_DIR_NAME

    def load(self) -> tuple[PluginRegistry, PluginImportResult]:
        """Import local plugins and return a fresh registry snapshot."""
        import_result = self._load_local_plugins()
        registry = default_registry(include_builtins=True)
        return registry, import_result

    def _load_local_plugins(self) -> PluginImportResult:
        loaded_paths: list[Path] = []
        diagnostics: list[DiagnosticItem] = []
        if not self._plugin_dir.exists():
            return PluginImportResult(tuple(), tuple())
        if not self._plugin_dir.is_dir():
            diagnostics.append(
                DiagnosticItem(
                    "warning",
                    f"{self._plugin_dir} exists but is not a directory.",
                    suggestion="Use a plugins/ directory containing local .py plugin modules.",
                )
            )
            return PluginImportResult(tuple(), tuple(diagnostics))

        root = str(self._project_root)
        if root not in sys.path:
            sys.path.insert(0, root)

        for path in sorted(self._plugin_dir.glob("*.py")):
            if path.name == "__init__.py":
                continue
            module_name = self._module_name(path)
            if module_name in sys.modules:
                loaded_paths.append(path)
                continue
            try:
                spec = importlib.util.spec_from_file_location(module_name, path)
                if spec is None or spec.loader is None:
                    raise ImportError(f"Cannot create an import spec for {path}")
                module = importlib.util.module_from_spec(spec)
                sys.modules[module_name] = module
                spec.loader.exec_module(module)
                loaded_paths.append(path)
            except DuplicatePluginRegistrationError as exc:
                sys.modules.pop(module_name, None)
                diagnostics.append(
                    DiagnosticItem(
                        "warning",
                        f"Plugin module {path.name} was already registered.",
                        cause=str(exc),
                        suggestion="Use unique plugin names or restart the Python process after editing plugins.",
                    )
                )
            except Exception as exc:  # noqa: BLE001 - local plugin import failures are diagnostics.
                sys.modules.pop(module_name, None)
                diagnostics.append(
                    DiagnosticItem(
                        "warning",
                        f"Could not import local plugin {path.name}.",
                        cause=str(exc),
                        suggestion="Fix the plugin import error. Configs that require it will fail validation.",
                    )
                )
        return PluginImportResult(tuple(loaded_paths), tuple(diagnostics))

    @staticmethod
    def _module_name(path: Path) -> str:
        digest = hashlib.sha1(str(path.resolve()).encode("utf-8")).hexdigest()[:12]
        return f"sef_local_plugins.{path.stem}_{digest}"


@dataclass(frozen=True, slots=True)
class ConfigInspectionResult:
    """Result of lightweight CLI schema inspection."""

    warnings: tuple[DiagnosticItem, ...]
    errors: tuple[DiagnosticItem, ...]

    @property
    def has_errors(self) -> bool:
        """Return True when strict inspection found blocking issues."""
        return bool(self.errors)


class ConfigInspector:
    """Performs practical CLI config checks before the core builder runs."""

    _TOP_LEVEL_KEYS = frozenset({"schema_version", "pipeline"})
    _PIPELINE_KEYS = frozenset(
        {
            "frame_extractor",
            "frame_processors",
            "signal_extractor",
            "signal_cleaners",
            "analyzers",
            "visualizers",
            "intermediate_frames",
            "runtime",
        }
    )
    _COMPONENT_KEYS = frozenset({"name", "params", "processor_type", "result_indices"})
    _INTERMEDIATE_FRAME_KEYS = frozenset(
        {
            "enabled",
            "sampling_interval",
            "max_stored_frames",
            "export_directory",
            "lazy_saving",
            "visualizers",
        }
    )
    _RUNTIME_KEYS = frozenset({"frame_buffer_size", "signal_buffer_size", "data_buffer_size", "latency_policy"})
    _LATENCY_POLICY_KEYS = frozenset({"name", "params"})

    def inspect(self, config: Mapping[str, Any], *, strict: bool = False) -> ConfigInspectionResult:
        """Return unknown-field diagnostics for the public config shape."""
        warnings: list[DiagnosticItem] = []
        errors: list[DiagnosticItem] = []

        self._unknown_keys(config, self._TOP_LEVEL_KEYS, "config", strict, warnings, errors)
        pipeline = config.get("pipeline")
        if isinstance(pipeline, Mapping):
            self._inspect_pipeline(pipeline, strict, warnings, errors)

        return ConfigInspectionResult(tuple(warnings), tuple(errors))

    def _inspect_pipeline(
        self,
        pipeline: Mapping[str, Any],
        strict: bool,
        warnings: list[DiagnosticItem],
        errors: list[DiagnosticItem],
    ) -> None:
        self._unknown_keys(pipeline, self._PIPELINE_KEYS, "pipeline", strict, warnings, errors)
        self._inspect_component(pipeline.get("frame_extractor"), "pipeline.frame_extractor", strict, warnings, errors)
        self._inspect_component(pipeline.get("signal_extractor"), "pipeline.signal_extractor", strict, warnings, errors)
        self._inspect_component_list(pipeline.get("frame_processors", ()), "pipeline.frame_processors", strict, warnings, errors)
        self._inspect_component_list(pipeline.get("signal_cleaners", ()), "pipeline.signal_cleaners", strict, warnings, errors)
        self._inspect_component_list(pipeline.get("analyzers", ()), "pipeline.analyzers", strict, warnings, errors)
        self._inspect_component_list(pipeline.get("visualizers", ()), "pipeline.visualizers", strict, warnings, errors)
        self._inspect_intermediate_frames(pipeline.get("intermediate_frames"), strict, warnings, errors)
        self._inspect_runtime(pipeline.get("runtime"), strict, warnings, errors)

    def _inspect_component_list(
        self,
        value: Any,
        path: str,
        strict: bool,
        warnings: list[DiagnosticItem],
        errors: list[DiagnosticItem],
    ) -> None:
        if not isinstance(value, list):
            return
        for index, item in enumerate(value):
            self._inspect_component(item, f"{path}[{index}]", strict, warnings, errors)

    def _inspect_component(
        self,
        value: Any,
        path: str,
        strict: bool,
        warnings: list[DiagnosticItem],
        errors: list[DiagnosticItem],
    ) -> None:
        if not isinstance(value, Mapping):
            return
        self._unknown_keys(value, self._COMPONENT_KEYS, path, strict, warnings, errors)

    def _inspect_intermediate_frames(
        self,
        value: Any,
        strict: bool,
        warnings: list[DiagnosticItem],
        errors: list[DiagnosticItem],
    ) -> None:
        if not isinstance(value, Mapping):
            return
        self._unknown_keys(value, self._INTERMEDIATE_FRAME_KEYS, "pipeline.intermediate_frames", strict, warnings, errors)
        self._inspect_component_list(
            value.get("visualizers", ()),
            "pipeline.intermediate_frames.visualizers",
            strict,
            warnings,
            errors,
        )

    def _inspect_runtime(
        self,
        value: Any,
        strict: bool,
        warnings: list[DiagnosticItem],
        errors: list[DiagnosticItem],
    ) -> None:
        if not isinstance(value, Mapping):
            return
        self._unknown_keys(value, self._RUNTIME_KEYS, "pipeline.runtime", strict, warnings, errors)
        latency_policy = value.get("latency_policy")
        if isinstance(latency_policy, Mapping):
            self._unknown_keys(
                latency_policy,
                self._LATENCY_POLICY_KEYS,
                "pipeline.runtime.latency_policy",
                strict,
                warnings,
                errors,
            )

    @staticmethod
    def _unknown_keys(
        value: Mapping[str, Any],
        allowed: frozenset[str],
        path: str,
        strict: bool,
        warnings: list[DiagnosticItem],
        errors: list[DiagnosticItem],
    ) -> None:
        for key in sorted(str(item) for item in value.keys()):
            if key in allowed:
                continue
            item = DiagnosticItem(
                "error" if strict else "warning",
                f"Unknown field `{path}.{key}`.",
                cause="This field is not part of the current public SEF config schema.",
                suggestion=_UNKNOWN_FIELD_DOC,
            )
            if strict:
                errors.append(item)
            else:
                warnings.append(item)


class ArtifactWriter:
    """Persists run summaries, normalized config, execution plans, and artifacts."""

    def __init__(self, output_dir: Path | str) -> None:
        self._output_dir = Path(output_dir)
        self._artifact_dir = self._output_dir / "artifacts"
        self.warnings: list[DiagnosticItem] = []

    def write(
        self,
        *,
        outputs: PipelineOutputs | None,
        config: Mapping[str, Any],
        execution_plan: PipelineExecutionPlan,
        dry_run: bool = False,
    ) -> list[Path]:
        """Persist supported output files and return created paths."""
        self._output_dir.mkdir(parents=True, exist_ok=True)
        created: list[Path] = []
        created.append(self._write_json("config.normalized.json", dict(config)))
        created.append(self._write_json("execution_plan.json", execution_plan.as_dict()))
        created.append(self._write_text("execution_plan.txt", execution_plan.as_text()))

        if outputs is not None:
            created.append(self._write_json("summary.json", self._summary(outputs, dry_run=dry_run)))
            created.extend(self._write_artifacts(outputs))
            reproducibility = outputs.metadata.reproducibility
            if reproducibility.get("yaml"):
                created.append(self._write_text("reproducibility.pipeline.yaml", str(reproducibility["yaml"])))
            if reproducibility.get("python_builder_code"):
                created.append(self._write_text("reproducibility.pipeline.py", str(reproducibility["python_builder_code"])))
        else:
            created.append(
                self._write_json(
                    "summary.json",
                    {
                        "dry_run": True,
                        "generated_at": datetime.now(timezone.utc).isoformat(),
                        "results": 0,
                        "artifacts": 0,
                    },
                )
            )
        return created

    def _write_artifacts(self, outputs: PipelineOutputs) -> list[Path]:
        created: list[Path] = []
        self._artifact_dir.mkdir(parents=True, exist_ok=True)
        for channel, artifacts in (("final", outputs.final_artifacts), ("debug", outputs.debug_artifacts)):
            for index, artifact in enumerate(artifacts):
                path = self._write_artifact(channel, index, artifact)
                if path is not None:
                    created.append(path)
        return created

    def _write_artifact(self, channel: str, index: int, artifact: VisualArtifact) -> Path | None:
        stem = self._artifact_stem(channel, index, artifact)
        try:
            if isinstance(artifact, TextArtifact):
                suffix = ".txt" if artifact.content_type == "text/plain" else ".md"
                return self._write_text(self._artifact_name(stem, suffix), artifact.content, base_dir=self._artifact_dir)
            if isinstance(artifact, JsonArtifact):
                return self._write_json(self._artifact_name(stem, ".json"), dict(artifact.payload), base_dir=self._artifact_dir)
            if isinstance(artifact, TableArtifact):
                payload = {"columns": list(artifact.columns), "rows": [dict(row) for row in artifact.rows]}
                return self._write_json(self._artifact_name(stem, ".table.json"), payload, base_dir=self._artifact_dir)
            if isinstance(artifact, ImageArtifact):
                return self._write_bytes(self._artifact_name(stem, self._mime_suffix(artifact.mime_type, ".png")), artifact.data)
            if isinstance(artifact, VideoArtifact):
                return self._write_bytes(self._artifact_name(stem, self._mime_suffix(artifact.mime_type, ".mp4")), artifact.data)
            if isinstance(artifact, VideoFileArtifact):
                suffix = Path(artifact.path).suffix or self._mime_suffix(artifact.mime_type, ".mp4")
                target = self._artifact_dir / self._artifact_name(stem, suffix)
                shutil.copy2(artifact.path, target)
                return target
            if isinstance(artifact, DeferredVideoArtifact):
                materialized = artifact.materialize(self._artifact_dir)
                target = self._artifact_dir / self._artifact_name(stem, Path(materialized).suffix or ".mp4")
                if Path(materialized) != target:
                    shutil.copy2(materialized, target)
                return target
        except Exception as exc:  # noqa: BLE001 - artifact export should be best-effort.
            self.warnings.append(
                DiagnosticItem(
                    "warning",
                    f"Could not export artifact {artifact.artifact_id}.",
                    cause=str(exc),
                    suggestion="Inspect the artifact manually or re-run with --debug for the pipeline traceback.",
                )
            )
            return None

        self.warnings.append(
            DiagnosticItem(
                "warning",
                f"Unsupported artifact type {type(artifact).__name__} for {artifact.artifact_id}.",
                suggestion="The run completed; only this artifact was skipped by the CLI writer.",
            )
        )
        return None

    def _write_json(self, filename: str, payload: Mapping[str, Any], *, base_dir: Path | None = None) -> Path:
        target = (base_dir or self._output_dir) / filename
        target.write_text(json_dumps(payload), encoding="utf-8")
        return target

    def _write_text(self, filename: str, content: str, *, base_dir: Path | None = None) -> Path:
        target = (base_dir or self._output_dir) / filename
        target.write_text(content if content.endswith("\n") else f"{content}\n", encoding="utf-8")
        return target

    def _write_bytes(self, filename: str, data: bytes) -> Path:
        target = self._artifact_dir / filename
        target.write_bytes(data)
        return target

    @staticmethod
    def _summary(outputs: PipelineOutputs, *, dry_run: bool) -> dict[str, Any]:
        return {
            "dry_run": dry_run,
            "pipeline_id": outputs.metadata.pipeline_id,
            "generated_at": outputs.metadata.generated_at.isoformat(),
            "results": len(outputs.results),
            "artifacts": outputs.artifact_count,
            "final_artifacts": len(outputs.final_artifacts),
            "debug_artifacts": len(outputs.debug_artifacts),
            "execution_metadata": to_exportable_data(outputs.metadata.execution_metadata),
        }

    @staticmethod
    def _artifact_stem(channel: str, index: int, artifact: VisualArtifact) -> str:
        safe_id = "".join(ch if ch.isalnum() or ch in ("-", "_") else "_" for ch in artifact.artifact_id)
        return f"{channel}_{index:02d}_{artifact.kind}_{safe_id}"

    @staticmethod
    def _artifact_name(stem: str, suffix: str) -> str:
        return f"{stem}{suffix}"

    @staticmethod
    def _mime_suffix(mime_type: str, default: str) -> str:
        mapping = {
            "image/png": ".png",
            "image/jpeg": ".jpg",
            "image/jpg": ".jpg",
            "image/webp": ".webp",
            "video/mp4": ".mp4",
            "video/quicktime": ".mov",
            "application/json": ".json",
        }
        return mapping.get(mime_type.lower(), default)


def _init_project(args: argparse.Namespace) -> int:
    root = Path.cwd()
    template = args.template or "default"
    created: list[Path] = []
    skipped: list[Path] = []

    for directory in (root / _PLUGIN_DIR_NAME, root / _VIDEO_DIR_NAME, root / _OUTPUT_DIR_NAME):
        if directory.exists():
            skipped.append(directory)
            continue
        directory.mkdir(parents=True, exist_ok=True)
        created.append(directory)

    files = _scaffold_files(template)
    for relative_path, content in files.items():
        target = root / relative_path
        if target.exists() and not _can_overwrite_scaffold(target, force=bool(args.force)):
            skipped.append(target)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        created.append(target)

    print(f"initialized: {root}")
    print(f"template: {template}")
    for path in created:
        print(f"created: {path.relative_to(root)}")
    for path in skipped:
        print(f"skipped: {path.relative_to(root)}")
    if skipped and not args.force:
        print("hint: use --force to overwrite SEF scaffold files that contain the scaffold marker.")
    return 0


def _doctor(args: argparse.Namespace) -> int:
    diagnostics = CliDiagnostics()
    _print_info("doctor")
    _doctor_python(diagnostics)
    _doctor_installation()
    _doctor_dependencies(diagnostics)
    _doctor_opencv_trackers(diagnostics)
    _doctor_matplotlib_cache(diagnostics)
    _doctor_project_directories(diagnostics)

    registry, import_result = CliRegistryLoader().load()
    diagnostics.extend(import_result.diagnostics)
    _print_ok(f"registered_components={len(registry.list())}")
    _print_ok(f"local_plugin_modules={len(import_result.loaded_paths)}")

    if args.config:
        try:
            raw_config, config = _load_config_with_raw(args.config)
            inspection = _inspect_cli_config(raw_config, config, strict=False)
            diagnostics.extend(inspection.warnings)
            diagnostics.extend(inspection.errors)
            from_config(config, registry=registry).build_context()
            _print_ok(f"config_valid={args.config}")
        except Exception as exc:  # noqa: BLE001 - doctor keeps scanning but exits non-zero for blockers.
            diagnostics.add_error(
                f"Config check failed for {args.config}.",
                cause=str(exc),
                suggestion="Fix the config path/schema or run `sef validate <config> --strict`.",
            )

    diagnostics.print()
    return diagnostics.exit_code()


def _run_pipeline(args: argparse.Namespace) -> int:
    registry, import_result = CliRegistryLoader().load()
    diagnostics = CliDiagnostics(list(import_result.diagnostics))
    raw_config, config = _load_config_with_raw(args.config)
    inspection = _inspect_cli_config(raw_config, config, strict=False)
    diagnostics.extend(inspection.warnings)
    diagnostics.extend(inspection.errors)
    if diagnostics.has_errors:
        diagnostics.print()
        return diagnostics.exit_code()

    facade = from_config(config, pipeline_id=args.pipeline_id, registry=registry)
    plan = facade.execution_plan()
    if args.explain:
        print(plan.as_text())
        _print_materialization_boundaries(plan)

    if args.dry_run:
        print(f"dry_run: {args.config}")
        print(f"schema_version: {config.get('schema_version')}")
        print(f"registered_components: {len(registry.list())}")
        if args.output:
            writer = ArtifactWriter(args.output)
            writer.write(outputs=None, config=config, execution_plan=plan, dry_run=True)
            diagnostics.extend(writer.warnings)
            print(f"output: {Path(args.output).resolve()}")
        diagnostics.print()
        return diagnostics.exit_code()

    outputs = facade.run()
    print(f"pipeline_id: {outputs.metadata.pipeline_id}")
    print(f"results: {len(outputs.results)}")
    print(f"artifacts: {outputs.artifact_count}")

    if args.output:
        writer = ArtifactWriter(args.output)
        writer.write(outputs=outputs, config=config, execution_plan=plan, dry_run=False)
        diagnostics.extend(writer.warnings)
        print(f"output: {Path(args.output).resolve()}")

    diagnostics.print()
    return diagnostics.exit_code()


def _validate_pipeline(args: argparse.Namespace) -> int:
    registry, import_result = CliRegistryLoader().load()
    diagnostics = CliDiagnostics(list(import_result.diagnostics))
    raw_config, config = _load_config_with_raw(args.config)
    inspection = _inspect_cli_config(raw_config, config, strict=bool(args.strict))
    diagnostics.extend(inspection.warnings)
    diagnostics.extend(inspection.errors)
    if diagnostics.has_errors:
        diagnostics.print()
        return diagnostics.exit_code()

    context = from_config(config, registry=registry).build_context()
    print(f"valid: {args.config}")
    print(f"schema_version: {context.source_config.get('schema_version')}")
    print(f"analyzers: {len(context.analyzers)}")
    print(f"visualizers: {len(context.visualizers) + len(context.visualizer_bindings)}")
    diagnostics.print()
    return diagnostics.exit_code()


def _list_components(args: argparse.Namespace) -> int:
    registry, import_result = CliRegistryLoader().load()
    descriptors = _component_descriptors(registry.describe(args.category))
    diagnostics = CliDiagnostics(list(import_result.diagnostics))
    if args.json:
        print(json.dumps(descriptors, indent=2, sort_keys=True))
        diagnostics.print()
        return diagnostics.exit_code()

    if not descriptors:
        print("No components registered.")
        diagnostics.print()
        return diagnostics.exit_code()

    for descriptor in descriptors:
        description = descriptor.get("description") or "-"
        print(f"{descriptor['category']:<24} {descriptor['name']:<28} {description}")
    diagnostics.print()
    return diagnostics.exit_code()


def _inspect_component(args: argparse.Namespace) -> int:
    registry, import_result = CliRegistryLoader().load()
    diagnostics = CliDiagnostics(list(import_result.diagnostics))
    matches = _find_component_matches(registry, args.name, category=args.category)
    if not matches:
        diagnostics.add_error(
            f"Component `{args.name}` was not found.",
            cause="No registered builtin or local plugin matches that name or alias.",
            suggestion="Run `sef components list` or check local plugin import warnings.",
        )
        diagnostics.print()
        return 1
    if len(matches) > 1:
        categories = ", ".join(sorted(definition.category for definition in matches))
        diagnostics.add_error(
            f"Component `{args.name}` is ambiguous across categories: {categories}.",
            suggestion="Re-run with `--category <category>`.",
        )
        diagnostics.print()
        return 1

    payload = _component_inspection(matches[0])
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        _print_component_inspection(payload)
    diagnostics.print()
    return diagnostics.exit_code()


def _version(_args: argparse.Namespace) -> int:
    version = _sef_distribution_version()
    print(f"sef: {version}")
    print(f"python: {platform.python_version()} ({sys.executable})")
    print(f"install_path: {Path(sef.__file__).resolve()}")
    print(f"mode: {_installation_mode()}")
    return 0


def _config_schema(args: argparse.Namespace) -> int:
    schema = _public_config_schema()
    if args.format == "yaml":
        print(yaml_dumps(schema), end="")
    else:
        print(json.dumps(schema, indent=2, sort_keys=False))
    return 0


def _component_descriptors(descriptors: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(descriptors, key=lambda item: (str(item["category"]), str(item["name"])))


def _load_config_with_raw(path: str | Path) -> tuple[dict[str, Any], dict[str, Any]]:
    config_path = Path(path)
    raw_text = config_path.read_text(encoding="utf-8")
    suffix = config_path.suffix.lower()
    if suffix == ".json":
        raw = json.loads(raw_text)
    elif suffix in {".yaml", ".yml"}:
        raw = _load_yaml_raw(raw_text, config_path)
    else:
        raise ConfigSchemaError(
            f"Unsupported config file extension '{config_path.suffix}'. Use .json, .yaml, or .yml.",
            path=str(config_path),
        )
    if not isinstance(raw, Mapping):
        raise ConfigSchemaError("'config' must be a mapping.", path=str(config_path))
    return dict(raw), normalize_config(raw)


def _load_yaml_raw(raw_text: str, config_path: Path) -> Any:
    try:
        import yaml
    except ImportError as exc:
        raise ConfigSchemaError(
            "YAML config loading requires PyYAML. Install SEF with its declared runtime dependencies.",
            path=str(config_path),
            cause=exc,
        ) from exc
    return yaml.safe_load(raw_text)


def _inspect_cli_config(
    raw_config: Mapping[str, Any],
    normalized_config: Mapping[str, Any],
    *,
    strict: bool,
) -> ConfigInspectionResult:
    config_to_inspect = raw_config if "pipeline" in raw_config else normalized_config
    return ConfigInspector().inspect(config_to_inspect, strict=strict)


def _find_component_matches(
    registry: PluginRegistry,
    name: str,
    *,
    category: str | None = None,
) -> list[PluginDefinition]:
    categories = (category,) if category else tuple(category.value for category in PluginCategory)
    matches: list[PluginDefinition] = []
    for category_name in categories:
        try:
            matches.append(registry.get(category_name, name))
        except KeyError:
            continue
    unique: dict[tuple[str, str], PluginDefinition] = {}
    for definition in matches:
        unique[(definition.category, definition.name)] = definition
    return list(unique.values())


def _component_inspection(definition: PluginDefinition) -> dict[str, Any]:
    signature_info = _signature_info(definition)
    capabilities = _definition_capabilities(definition)
    payload = {
        **definition.as_dict(),
        "signature": signature_info["signature"],
        "required_params": signature_info["required_params"],
        "optional_params": signature_info["optional_params"],
        "var_params": signature_info["var_params"],
        "capabilities": capabilities.as_dict() if capabilities else None,
        "streaming": bool(capabilities.supports_streaming) if capabilities else None,
        "input": _category_input(definition.category),
        "output": _category_output(definition.category),
    }
    payload["yaml_example"] = _yaml_component_snippet(definition)
    payload["python_example"] = _python_component_snippet(definition)
    return payload


def _print_component_inspection(payload: Mapping[str, Any]) -> None:
    print(f"name: {payload['name']}")
    print(f"category: {payload['category']}")
    print(f"description: {payload.get('description') or '-'}")
    print(f"version: {payload.get('version')}")
    print(f"aliases: {', '.join(payload.get('aliases') or []) or '-'}")
    print(f"factory: {payload.get('factory_path')}")
    print(f"signature: {payload.get('signature')}")
    print(f"required_params: {', '.join(payload.get('required_params') or []) or '-'}")
    optional = payload.get("optional_params") or {}
    if optional:
        print("optional_params:")
        for name, default in optional.items():
            print(f"  - {name}={default}")
    else:
        print("optional_params: -")
    capabilities = payload.get("capabilities")
    if capabilities:
        print("capabilities:")
        for key, value in capabilities.items():
            print(f"  - {key}: {value}")
    else:
        print("capabilities: unknown without instantiation")
    print(f"input: {payload.get('input')}")
    print(f"output: {payload.get('output')}")
    metadata = payload.get("metadata") or {}
    print(f"metadata: {json.dumps(metadata, sort_keys=True)}")
    print("yaml_example:")
    print(payload["yaml_example"])
    print("python_example:")
    print(payload["python_example"])


def _signature_info(definition: PluginDefinition) -> dict[str, Any]:
    target = _signature_target(definition)
    try:
        signature = inspect.signature(target)
    except (TypeError, ValueError):
        return {"signature": "unknown", "required_params": [], "optional_params": {}, "var_params": []}

    parameters = list(signature.parameters.values())
    parameters = _drop_non_config_parameters(parameters, definition.category)
    required: list[str] = []
    optional: dict[str, str] = {}
    var_params: list[str] = []
    for parameter in parameters:
        if parameter.kind in (inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD):
            var_params.append(parameter.name)
            continue
        if parameter.default is inspect.Parameter.empty:
            required.append(parameter.name)
        else:
            optional[parameter.name] = repr(parameter.default)
    return {
        "signature": str(signature),
        "required_params": required,
        "optional_params": optional,
        "var_params": var_params,
    }


def _signature_target(definition: PluginDefinition) -> Any:
    factory = definition.factory
    if inspect.isclass(factory):
        return factory.__init__
    original = _closure_callable(factory)
    if original is not None:
        return original
    metadata_function = definition.metadata.get("function")
    if isinstance(metadata_function, str):
        resolved = _resolve_dotted_path(metadata_function)
        if resolved is not None:
            return resolved
    return factory


def _closure_callable(factory: Any) -> Any | None:
    closure = getattr(factory, "__closure__", None) or ()
    for cell in closure:
        try:
            value = cell.cell_contents
        except ValueError:
            continue
        if callable(value) and value is not factory:
            return value
    return None


def _resolve_dotted_path(path: str) -> Any | None:
    module_name, _, attr_path = path.partition(":") if ":" in path else path.rpartition(".")
    if not module_name or not attr_path:
        return None
    try:
        module = importlib.import_module(module_name)
    except Exception:
        return None
    target: Any = module
    for part in attr_path.split("."):
        target = getattr(target, part, None)
        if target is None:
            return None
    return target


def _drop_non_config_parameters(
    parameters: list[inspect.Parameter],
    category: str,
) -> list[inspect.Parameter]:
    if parameters and parameters[0].name == "self":
        parameters = parameters[1:]
    if not parameters:
        return parameters
    input_first_categories = {
        PluginCategory.SINGLE_FRAME_PROCESSOR.value,
        PluginCategory.SIGNAL_EXTRACTOR.value,
        PluginCategory.SIGNAL_CLEANER.value,
        PluginCategory.ANALYZER.value,
        PluginCategory.VISUALIZER.value,
    }
    if category in input_first_categories and parameters[0].name not in {"config", "params"}:
        parameters = parameters[1:]
    return [parameter for parameter in parameters if parameter.name != "context"]


def _definition_capabilities(definition: PluginDefinition) -> StageCapabilities | None:
    factory = definition.factory
    capabilities = getattr(factory, "capabilities", None)
    if isinstance(capabilities, StageCapabilities):
        return capabilities
    return None


def _category_input(category: str) -> str:
    return {
        PluginCategory.FRAME_EXTRACTOR.value: "none",
        PluginCategory.SINGLE_FRAME_PROCESSOR.value: "Frame or frame image",
        PluginCategory.FRAME_BUFFER_PROCESSOR.value: "FrameBuffer",
        PluginCategory.SIGNAL_EXTRACTOR.value: "FrameBuffer",
        PluginCategory.SIGNAL_CLEANER.value: "ISignal",
        PluginCategory.ANALYZER.value: "ISignal",
        PluginCategory.VISUALIZER.value: "IData analysis result",
        PluginCategory.BRANCHING_RULE.value: "Pipeline trigger event",
    }.get(category, "unknown")


def _category_output(category: str) -> str:
    return {
        PluginCategory.FRAME_EXTRACTOR.value: "FrameBuffer",
        PluginCategory.SINGLE_FRAME_PROCESSOR.value: "Frame",
        PluginCategory.FRAME_BUFFER_PROCESSOR.value: "FrameBuffer or FrameExportResult",
        PluginCategory.SIGNAL_EXTRACTOR.value: "ISignal",
        PluginCategory.SIGNAL_CLEANER.value: "ISignal",
        PluginCategory.ANALYZER.value: "IData",
        PluginCategory.VISUALIZER.value: "tuple[VisualArtifact, ...]",
        PluginCategory.BRANCHING_RULE.value: "branch decision",
    }.get(category, "unknown")


def _yaml_component_snippet(definition: PluginDefinition) -> str:
    params = _example_params(definition)
    body: dict[str, Any] = {"name": definition.name}
    if params:
        body["params"] = params
    if definition.category in {
        PluginCategory.SINGLE_FRAME_PROCESSOR.value,
        PluginCategory.FRAME_BUFFER_PROCESSOR.value,
    }:
        body["processor_type"] = "frame_buffer" if definition.category == PluginCategory.FRAME_BUFFER_PROCESSOR.value else "single_frame"
    return yaml_dumps(body).rstrip()


def _python_component_snippet(definition: PluginDefinition) -> str:
    method = {
        PluginCategory.FRAME_EXTRACTOR.value: "frames",
        PluginCategory.SINGLE_FRAME_PROCESSOR.value: "process",
        PluginCategory.FRAME_BUFFER_PROCESSOR.value: "process",
        PluginCategory.SIGNAL_EXTRACTOR.value: "signals",
        PluginCategory.SIGNAL_CLEANER.value: "clean",
        PluginCategory.ANALYZER.value: "analyze",
        PluginCategory.VISUALIZER.value: "visualize",
    }.get(definition.category, "register")
    params = _example_params(definition)
    if params:
        formatted = ", ".join(f"{key}=..." for key in params)
        return f"sef.pipeline(include_builtins=True).{method}({definition.name!r}, {formatted})"
    return f"sef.pipeline(include_builtins=True).{method}({definition.name!r})"


def _example_params(definition: PluginDefinition) -> dict[str, str]:
    info = _signature_info(definition)
    return {name: "<required>" for name in info["required_params"] if name not in {"config", "buffer"}}


def _print_materialization_boundaries(plan: PipelineExecutionPlan) -> None:
    if not plan.materialization_boundaries:
        print("materialization_boundaries: none")
        return
    print("materialization_boundaries:")
    for stage in plan.materialization_boundaries:
        print(f"- {stage.stage_id}: {stage.component_name}")


def _doctor_python(diagnostics: CliDiagnostics) -> None:
    version = sys.version_info
    if version < (3, 11):
        diagnostics.add_error(
            f"Python {platform.python_version()} is not supported.",
            cause="SEF uses Python 3.11+ language/runtime features.",
            suggestion="Create a Python 3.11+ environment and reinstall SEF.",
        )
    else:
        _print_ok(f"python={platform.python_version()}")


def _doctor_installation() -> None:
    _print_ok(f"sef_version={_sef_distribution_version()}")
    _print_ok(f"install_path={Path(sef.__file__).resolve()}")
    _print_ok(f"install_mode={_installation_mode()}")


def _doctor_dependencies(diagnostics: CliDiagnostics) -> None:
    required = {"numpy": "numpy", "yaml": "PyYAML"}
    optional = {
        "cv2": ("opencv", "opencv-contrib-python"),
        "matplotlib": ("visualization", "matplotlib"),
        "streamlit": ("ui", "streamlit"),
        "ultralytics": ("yolo", "ultralytics"),
        "joblib": ("pose", "joblib"),
    }
    for module_name, package_name in required.items():
        if _module_importable(module_name):
            _print_ok(f"core_dependency={package_name}")
        else:
            diagnostics.add_error(
                f"Missing dependency `{package_name}`.",
                cause=f"Python cannot import `{module_name}`.",
                suggestion="Install project dependencies with `pip install -e .` or `pip install -r requirements.txt`.",
            )
    for module_name, (extra_name, package_name) in optional.items():
        if _module_importable(module_name):
            _print_ok(f"optional_extra={extra_name} dependency={package_name}")
        else:
            diagnostics.add_warning(
                f"Optional extra `{extra_name}` is not available because `{package_name}` is not importable.",
                suggestion=f"Install it only if you use that feature: `pip install 'sef[{extra_name}]'`.",
            )


def _doctor_opencv_trackers(diagnostics: CliDiagnostics) -> None:
    try:
        import cv2  # type: ignore[import-not-found]
    except Exception as exc:  # noqa: BLE001 - doctor reports import diagnostics.
        diagnostics.add_warning(
            "OpenCV optional extra is not available.",
            cause=str(exc),
            suggestion="Install `sef[opencv]` if you need OpenCV-backed pipeline components.",
        )
        return

    tracker_names = ("MIL", "KCF", "CSRT", "MOSSE")
    available: list[str] = []
    for name in tracker_names:
        if hasattr(cv2, f"Tracker{name}_create") or hasattr(getattr(cv2, "legacy", object()), f"Tracker{name}_create"):
            available.append(name)
    if available:
        _print_ok(f"opencv_trackers={','.join(available)}")
    else:
        diagnostics.add_warning(
            "No common OpenCV tracker constructors were detected.",
            cause="The installed OpenCV build may not include tracking APIs.",
            suggestion="Install opencv-contrib-python if you need OpenCV tracker pipelines.",
        )


def _doctor_matplotlib_cache(diagnostics: CliDiagnostics) -> None:
    if not _module_importable("matplotlib"):
        return
    configured_cache = os.environ.get("MPLCONFIGDIR")
    if not configured_cache:
        _print_ok("matplotlib_cache=not_checked")
        return
    cache_dir = Path(configured_cache)
    if cache_dir.exists() and cache_dir.is_dir() and _path_writable(cache_dir):
        _print_ok(f"matplotlib_cache={cache_dir}")
        return
    diagnostics.add_warning(
        f"Matplotlib cache directory is not writable: {cache_dir}",
        suggestion="Set MPLCONFIGDIR to a writable directory to avoid startup warnings.",
    )


def _doctor_project_directories(diagnostics: CliDiagnostics) -> None:
    root = Path.cwd()
    for name in (_PLUGIN_DIR_NAME, _VIDEO_DIR_NAME, _OUTPUT_DIR_NAME):
        path = root / name
        if not path.exists():
            if name == _OUTPUT_DIR_NAME and _path_writable(root):
                diagnostics.add_warning(f"Directory `{name}/` does not exist.", suggestion="Run `sef init` to create it.")
            else:
                diagnostics.add_warning(f"Directory `{name}/` does not exist.", suggestion="Run `sef init` to create it.")
            continue
        if not path.is_dir():
            diagnostics.add_error(
                f"`{name}` exists but is not a directory.",
                suggestion="Move the file or choose a clean project directory.",
            )
            continue
        if name == _OUTPUT_DIR_NAME and not _path_writable(path):
            diagnostics.add_error(
                f"`{name}/` is not writable.",
                suggestion="Fix permissions or pass a writable --output directory when running pipelines.",
            )
        else:
            _print_ok(f"directory={name}/")


def _module_importable(module_name: str) -> bool:
    return importlib.util.find_spec(module_name) is not None


def _path_writable(path: Path) -> bool:
    return path.exists() and path.is_dir() and os_access(path, "w")


def os_access(path: Path, mode: str) -> bool:
    import os

    flag = os.W_OK if mode == "w" else os.R_OK
    return os.access(path, flag)


def _sef_distribution_version() -> str:
    try:
        return importlib.metadata.version("sef")
    except importlib.metadata.PackageNotFoundError:
        return "unknown"


def _installation_mode() -> str:
    path = Path(sef.__file__).resolve()
    cwd = Path.cwd().resolve()
    if cwd in path.parents:
        return "editable/local"
    return "package"


def _can_overwrite_scaffold(path: Path, *, force: bool) -> bool:
    if not path.exists():
        return True
    if not force:
        return False
    try:
        return _SCAFFOLD_FILE_MARKER in path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return False


def _scaffold_files(template: str) -> dict[str, str]:
    if template == "tracking-demo":
        return {
            _DEFAULT_CONFIG_NAME: _tracking_demo_pipeline_yaml(),
            "README.md": _tracking_demo_readme(),
            "plugins/example_local_plugins.py": _example_plugin_file(),
        }
    return {
        _DEFAULT_CONFIG_NAME: _default_pipeline_yaml(),
        "README.md": _default_readme(),
        "plugins/example_local_plugins.py": _example_plugin_file(),
    }


def _default_pipeline_yaml() -> str:
    return f"""{_SCAFFOLD_FILE_MARKER}
schema_version: "1.0"
pipeline:
  frame_extractor:
    name: opencv_buffered
    params:
      path: videos/input.mp4
      config:
        max_frames: 300

  frame_processors: []

  signal_extractor:
    name: opencv_tracker
    params:
      start_box: [100, 100, 80, 80]
      tracker_type: MIL

  signal_cleaners:
    - name: moving_average
      params:
        window: 5

  analyzers:
    - name: vertical_position

  visualizers:
    - name: matplotlib
      result_indices: [0]

  runtime:
    frame_buffer_size: 8
    signal_buffer_size: 8
    data_buffer_size: 8
"""


def _tracking_demo_pipeline_yaml() -> str:
    return f"""{_SCAFFOLD_FILE_MARKER}
# Put your demo video at videos/input.mp4 before running this pipeline.
schema_version: "1.0"
pipeline:
  frame_extractor:
    name: opencv_buffered
    params:
      path: videos/input.mp4
      config:
        max_frames: 300
        stride: 1

  frame_processors:
    - name: opencv_gray
      processor_type: single_frame

  signal_extractor:
    name: opencv_tracker
    params:
      start_box: [100, 100, 80, 80]
      tracker_type: MIL

  signal_cleaners:
    - name: moving_average
      params:
        window: 5

  analyzers:
    - name: vertical_position

  visualizers:
    - name: matplotlib
      result_indices: [0]

  intermediate_frames:
    enabled: false

  runtime:
    frame_buffer_size: 8
    signal_buffer_size: 8
    data_buffer_size: 8
"""


def _default_readme() -> str:
    return f"""{_SCAFFOLD_FILE_MARKER}
# SEF project

## Usage

1. Put an input video at `videos/input.mp4`.
2. Validate the pipeline:

```bash
sef validate pipeline.yaml --strict
```

3. Inspect the execution plan without running:

```bash
sef run pipeline.yaml --dry-run --explain
```

4. Run and collect outputs:

```bash
sef run pipeline.yaml --output outputs/run-001
```

Local plugins can be added as `.py` files under `plugins/` and registered with
decorators such as `@sef.analyzer("my_analyzer")`.
"""


def _tracking_demo_readme() -> str:
    return f"""{_SCAFFOLD_FILE_MARKER}
# SEF tracking demo

This scaffold is video-based but intentionally does not include media assets.
Place your video at:

```text
videos/input.mp4
```

Then run:

```bash
sef validate pipeline.yaml --strict
sef run pipeline.yaml --dry-run --explain
sef run pipeline.yaml --output outputs/tracking-demo
```

The default `start_box` in `pipeline.yaml` is `[100, 100, 80, 80]`. Adjust it to
match the object you want to track in your video.
"""


def _example_plugin_file() -> str:
    return f'''{_SCAFFOLD_FILE_MARKER}
from __future__ import annotations

import sef


@sef.analyzer("example_sample_counter")
def sample_counter(signal):
    """Return a simple count-like result for local plugin experiments."""
    return signal
'''


def _public_config_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "required": ["schema_version", "pipeline"],
        "properties": {
            "schema_version": {"type": "string", "example": "1.0"},
            "pipeline": {
                "type": "object",
                "required": ["frame_extractor", "signal_extractor", "analyzers"],
                "properties": {
                    "frame_extractor": _component_schema("frame_extractor"),
                    "frame_processors": {
                        "type": "array",
                        "items": {
                            **_component_schema("frame_processor"),
                            "properties": {
                                "name": {"type": "string"},
                                "params": {"type": "object"},
                                "processor_type": {"enum": ["single_frame", "frame_buffer"], "default": "single_frame"},
                            },
                        },
                    },
                    "signal_extractor": _component_schema("signal_extractor"),
                    "signal_cleaners": {"type": "array", "items": _component_schema("signal_cleaner")},
                    "analyzers": {"type": "array", "items": _component_schema("analyzer")},
                    "visualizers": {
                        "type": "array",
                        "items": {
                            **_component_schema("visualizer"),
                            "properties": {
                                "name": {"type": "string"},
                                "params": {"type": "object"},
                                "result_indices": {"type": "array", "items": {"type": "integer", "minimum": 0}},
                            },
                        },
                    },
                    "intermediate_frames": {
                        "type": "object",
                        "properties": {
                            "enabled": {"type": "boolean", "default": False},
                            "sampling_interval": {"type": "integer", "minimum": 1},
                            "max_stored_frames": {"type": "integer", "minimum": 1},
                            "export_directory": {"type": "string"},
                            "lazy_saving": {"type": "boolean"},
                            "visualizers": {"type": "array", "items": _component_schema("visualizer")},
                        },
                    },
                    "runtime": {
                        "type": "object",
                        "properties": {
                            "frame_buffer_size": {"type": "integer", "minimum": 1},
                            "signal_buffer_size": {"type": "integer", "minimum": 1},
                            "data_buffer_size": {"type": "integer", "minimum": 1},
                            "latency_policy": {
                                "type": "object",
                                "properties": {
                                    "name": {"type": "string", "example": "blocking"},
                                    "params": {"type": "object"},
                                },
                            },
                        },
                    },
                },
            },
        },
    }


def _component_schema(title: str) -> dict[str, Any]:
    return {
        "title": title,
        "type": "object",
        "required": ["name"],
        "properties": {
            "name": {"type": "string"},
            "params": {"type": "object", "additionalProperties": True},
        },
    }


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
