from __future__ import annotations

SCAFFOLD_FILE_MARKER = "# Generated by sef init"
DEFAULT_CONFIG_NAME = "pipeline.yaml"
PLUGIN_DIR_NAME = "plugins"
VIDEO_DIR_NAME = "videos"
OUTPUT_DIR_NAME = "outputs"
UNKNOWN_FIELD_DOC = "Remove the field or move custom values under params/metadata."
